name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        run: |
          curl -X POST https://server.knotten.net/webhook/ \
          -H 'Content-Type: application/json' \
          -d '{"repository": {"url": "https://github.com/knottem/fakestore-cart"}}'
